repos:
- repo: https://github.com/pocc/pre-commit-hooks # Check for unused variables in cpp code
  rev: v1.3.5
  hooks:
    - id: clang-format
      args: [--style=Google]
    - id: uncrustify
    - id: cppcheck
    - id: cpplint
    - id: include-what-you-use
- repo: https://github.com/asottile/seed-isort-config  # Helps isort determine third party imports
  rev: v2.2.0
  hooks:
    - id: seed-isort-config
- repo: https://github.com/pre-commit/mirrors-isort  # Sort imports, similar to PyCharm organize imports
  rev: v5.10.1
  hooks:
    - id: isort
      args: [ '-l=120', '-m=2' ]
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: no-commit-to-branch  # Prevents direct commits to master
  - id: check-ast  # check if valid python file in python file
    types: [python] # type of file to validate
  - id: check-merge-conflict  # check if left in merge conflict lines
  - id: debug-statements # check if left in debug statements in python files
    types: [python] # type of file to validate
  - id: trailing-whitespace  # remove trailing whitespace in python files
    types: [python] # type of file to validate
  - id: end-of-file-fixer  # have one line at end of file in python files
    types: [python] # type of file to validate
  - id: check-docstring-first  # File comments should come before imports
  - id: check-json  # make sure valid json
  - id: check-yaml  # make sure valid yaml
  - id: name-tests-test  # check that tests start with test_*
    args: ['--django']
  - id: requirements-txt-fixer  # sort requirements
  - id: check-added-large-files  # check that we're not committing big files to git, excluding lfs files.
    args: ['--maxkb=1000']  # set max file size to 1000KB
- repo: https://github.com/asottile/pyupgrade  # use Python3 tricks
  rev: v3.2.0
  hooks:
  - id: pyupgrade
    args: ['--keep-percent-format']
- repo: https://github.com/pre-commit/mirrors-autopep8  # Autoenforce easy pep8 changes.
  rev: v2.0.0
  hooks:
  - id: autopep8
    args: ['-i', '--max-line-length=120', '--ignore=W504']  # W504 is outdated and conflicts with W503
- repo: https://github.com/aflc/pre-commit-jupyter
  rev: v1.2.1
  hooks:
    - id: jupyter-notebook-cleanup
      args:
        - --remove-kernel-metadata
        - --pin-patterns
        - "[pin];[donotremove]"
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.982'
    hooks:
    -   id: mypy # A static type checker for Python 3 and Python 2.7.
        additional_dependencies:
          - types-protobuf==3.17.4
          - types-cachetools
          - types-ujson
          - types-requests
          - numpy
        args:
          - --ignore-missing-imports  # silence all import errors from untyped libraries
          - --follow-imports=silent  # follow imports but suppress all errors
          - --strict  # enable strict flags (e.g. untyped calls, decorators, optional)
          - --allow-subclassing-any  # allow subclassing from classes in silenced modules
          - --show-column-numbers  # add column offsets to error messages
          - --allow-untyped-decorators # allow decorating typed functions with untyped decorators (such as avtest)
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v14.0.6
    hooks:
    - id: clang-format