{
  "channels": [
    "defaults"
  ],
  "dependencies": [
    "python=3.8.5",
    "pytorch=1.7.0",
    "torchvision",
    "cudatoolkit=10.1"
  ],
  "name": "volsdf",
  "prefix": "/scratch/agassol/conda_envs/volsdf"
}
